services:
  - type: web
    name: chroma-server
    env: python
    plan: standard
    buildCommand: ""
    startCommand: chroma run --host 0.0.0.0 --port $PORT --path /data
    disk:
      name: chroma-data
      mountPath: /data
      sizeGB: 1
