services:
  - type: web
    name: chroma-server
    env: python
    plan: standard
    buildCommand: ""
    startCommand: chroma run --host 0.0.0.0 --port 10000 --path /chroma
    disk:
      name: chroma-data
      mountPath: /chroma
      sizeGB: 1
    envVars:
      - key: PORT
        value: "10000"
